[package]
name = "fp-consensus"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for Frontier consensus"
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[dependencies]
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", version = '3.0.0' }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", version = '3.0.0' }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", version = '3.0.0' }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = [
	"sp-std/std",
	"sp-runtime/std",
	"sp-core/std",
	"codec/std",
]
