[package]
authors = ['Anonymous']
build = 'build.rs'
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'node-template'
repository = 'https://github.com/paritytech/substrate/'
version = '2.0.0-alpha.5'

[build-dependencies]
vergen = '3.0.4'

[build-dependencies.build-script-utils]
package = 'substrate-build-script-utils'
version = '2.0.0-alpha.5'

[dependencies]
futures = '0.3.1'
log = '0.4.8'
structopt = '0.3.8'

[dependencies.ssvm]
package = 'pallet-ssvm'
git = 'https://github.com/second-state/pallet-ssvm'
tag = 'v0.0.1'

[dependencies.grandpa]
package = 'sc-finality-grandpa'
version = '0.8.0-alpha.5'

[dependencies.grandpa-primitives]
package = 'sp-finality-grandpa'
version = '2.0.0-alpha.5'

[dependencies.node-template-runtime]
path = '../runtime'
version = '2.0.0-alpha.5'

[dependencies.sc-basic-authorship]
version = '0.8.0-alpha.5'

[dependencies.sc-cli]
version = '0.8.0-alpha.5'

[dependencies.sc-client]
version = '0.8.0-alpha.5'

[dependencies.sc-client-api]
version = '2.0.0-alpha.5'

[dependencies.sc-consensus-aura]
version = '0.8.0-alpha.5'

[dependencies.sc-executor]
version = '0.8.0-alpha.5'

[dependencies.sc-network]
version = '0.8.0-alpha.5'

[dependencies.sc-service]
version = '0.8.0-alpha.5'

[dependencies.sc-transaction-pool]
version = '2.0.0-alpha.5'

[dependencies.sp-consensus]
version = '0.8.0-alpha.5'

[dependencies.sp-consensus-aura]
version = '0.8.0-alpha.5'

[dependencies.sp-core]
version = '2.0.0-alpha.5'

[dependencies.sp-inherents]
version = '2.0.0-alpha.5'

[dependencies.sp-runtime]
version = '2.0.0-alpha.5'

[dependencies.sp-transaction-pool]
version = '2.0.0-alpha.5'

[[bin]]
name = 'node-template'
