# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run.
# Triggers the workflow on push or pull request events
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  runs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: secondstate/substrate-ssvm

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Build substrate-ssvm-node
      run: |
        ln -sf /root/.rustup $HOME/
        ln -sf /root/.cargo $HOME/
        cargo build --release